name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.OS }}
    env:
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry-${{matrix.TARGET}}

      - name: run prisma generate
        run: cargo prisma generate

      - name: Install rust target
        run: rustup target add $TARGET

      - name: Run tests
        run: cargo test --verbose

      - name: Run fmt
        run: cargo fmt -- --check

      - name: Run build
        run: cargo build --release --verbose --target $TARGET
