name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.OS }}
    env:
      OS: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: run prisma generate
        run: cargo prisma generate

      - name: Run Check
        run: cargo clippy --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run fmt
        run: cargo fmt --all --check

      - name: Run build
        run: cargo build --release --verbose
